swagger: "2.0"
info:
  version: "0.0.1"
  title: Hello World App
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
#BB add security definition
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /hello:
    # binds a127 app logic to a route
    x-swagger-router-controller: hello_world
    get:
      description: Returns 'Hello' to the caller
      # used as the method name of the controller
      operationId: hello
      parameters:
        - name: name
          in: query
          description: The name of the person to whom to say hello
          required: false
          type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/HelloWorldResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
#AA add operation and it is a POST, note that you need to add CORS
    post:
      description: Returns 'Hello2' to the caller
      operationId: hello2
      parameters:
        - in: "body"
          name: "todo"
          description: "todo to be added"
          required: true
          schema:
            type: "object"
            properties:
              todo_id:
                type: "integer"
                description: "Id for the todo"
              todo:
                type: "string"
                description: "The todo item"
      responses:
        "200":
          description: Success
          schema:
            type: "object"
        default:
          description: Error
          schema:
            type: "object"
#BB security & new controller
  /login:
    post:
      description: "user login"
      operationId: "Login"
#      produces:
#        - "application/json"
      parameters:
      - in: "body"
        name: "my_cred"
        description: "credentials"
        required: true
        schema:
          type: "object"
      #    required:
      #      - username
      #      - password
          properties:
            username:
              type: "string"
            password:
              type: "string"
      responses:
        "200":
          description: "Success"
          schema:
            type: "object"
            properties:
              token:
                type: string
                description: "JWT"
        "401":
          description: "Error"
      x-swagger-router-controller: "Security"
  /test_protected:
    get:
      security:
        - Bearer: []
      operationId: "TestProtected"
#      produces:
#        - "text/plain; charset=utf-8"
      responses:
        "200":
          description: "TestProtected"
          schema: 
#            type: "string"
            type: "object"
        default:
          description: Error
          schema:
            type: "object"
      x-swagger-router-controller: "Security"
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  HelloWorldResponse:
    required:
      - message
    properties:
      message:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
